version: '3'

networks:
  proxytanet:
    external: true

services:
  app:
    build: .
    image: caracole/chantier
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.backend: "chantier"
      traefik.frontend.rule: "Host: caracole.${CHATONS_DOMAIN:-local}"
    networks:
      - proxytanet
